BASE_URL = https://raw.githubusercontent.com/git/git/master/contrib/completion/

all: git-prompt.sh git-completion.bash

git-prompt.sh:
	curl $(BASE_URL)/git-prompt.sh > git-prompt.sh

git-completion.bash:
	curl $(BASE_URL)/git-completion.bash > git-completion.bash
