[tools]
delta = "latest"
difftastic = "latest"
hub = "latest"
jq = "latest"
mcfly = "latest"
lsd = "latest"
shfmt = "latest"
shellcheck = "latest"
ripgrep = "latest"
"aqua:reviewdog/reviewdog" = "latest"
starship = "latest"
uv = "latest"

[alias]
delta = "aqua:dandavison/delta"
difftastic = "aqua:Wilfred/difftastic"
hub = "aqua:mislav/hub"
jq = "aqua:jqlang/jq"
mcfly = "aqua:cantino/mcfly"
lsd = "aqua:lsd-rs/lsd"
shfmt = "aqua:mvdan/sh"
shellcheck = "aqua:koalaman/shellcheck"
ripgrep = "aqua:BurntSushi/ripgrep"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
